---
services:
  php:
    restart: unless-stopped
    depends_on:
      - database
      - redis
    secrets:
      - database_password
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      DEFAULT_URI: https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}
      DATABASE_PASSWORD_FILE: /run/secrets/database_password
      CADDY_SERVER_LOG_OPTIONS: |
        output stdout
      CADDY_EXTRA_CONFIG: |
        import /etc/frankenphp/conf.d/*.caddy
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - name: http
        target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - name: https
        target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - name: http3
        target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

  redis:
    image: redis:8.8
    ulimits:
      memlock: -1
    volumes:
      - redis_data:/data

###> doctrine/doctrine-bundle ###
  database:
    image: ${IMAGES_PREFIX:-}app-postgresql
    build:
      context: postgresql
    secrets:
      - database_password
      - role_backup_password
      - role_reporting_password
    environment:
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=fr-FR
      POSTGRES_DB: ${DATABASE_DB:-app}
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
      POSTGRES_USER: ${DATABASE_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${DATABASE_DB:-app}", "-U", "${DATABASE_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql:rw
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
      - ./postgresql/data:/data/app
###< doctrine/doctrine-bundle ###

# Le profil empêche le service d'être créer dans la configuration par défaut.
  k6:
    image: grafana/k6:latest
    profiles:
      - bench
    environment:
      K6_PROMETHEUS_RW_SERVER_URL: http://victoriametrics:8428/api/v1/write
    volumes:
      - ./performance/k6:/scripts:ro
    working_dir: /scripts

  gotenberg:
    image: gotenberg/gotenberg:8

volumes:
  caddy_data:
  caddy_config:
  redis_data:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

secrets:
  database_password:
    file: ./secrets/database_password
  role_backup_password:
    file: ./secrets/role_backup_password
  role_reporting_password:
    file: ./secrets/role_reporting_password
  admin_password:
    file: ./secrets/admin_password
