apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres

    url: database:5432

    user: grafana

    secureJsonData:
      password: $__file{/run/secrets/role_grafana_password}

    jsonData:
      database: app
      sslmode: disable
      postgresVersion: 1800
      timescaledb: false

    editable: false
