apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres

    url: database:5432

    user: reporting

    secureJsonData:
      password: $__file{/run/secrets/role_reporting_password}

    jsonData:
      database: app
      sslmode: disable
      postgresVersion: 1800
      timescaledb: false

    editable: false
