<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260804135028 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'User';
    }

    public function up(Schema $schema): void
    {
        $dbName = $this->connection->getDatabase();

        $this->addSql('create schema if not exists reporting;');
        $this->addSql(sprintf('grant connect on database "%s" to reporting;', $dbName));
        $this->addSql(sprintf('alter role reporting in database "%s" set search_path = reporting;', $dbName));
        $this->addSql('grant usage on schema reporting to reporting;');
        $this->addSql('alter default privileges in schema reporting grant select on tables to reporting;');

        $this->addSql(<<<SQL
        create table "user" (
            id bigint generated by default as identity not null,
            "email" text not null,
            "roles" jsonb not null,
            "password" text not null,
            primary key (id)
        )
        SQL);

        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');

        $this->addSql(<<<SQL
        create table messenger_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            body TEXT NOT NULL,
            headers TEXT NOT NULL,
            queue_name VARCHAR(190) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )
        SQL);

        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('drop table "user"');
        $this->addSql('drop table messenger_messages');

        $this->addSql('drop view reporting.audit');
        $this->addSql('drop table audit');
        $this->addSql('drop table "user"');
        $this->addSql('drop schema reporting cascade;');
    }
}
