<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260804155512 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Audit';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<SQL
        create table audit (
            id bigint primary key generated by default as identity,
            created_at timestamptz default current_timestamp not null,
            "action" text not null,
            user_id bigint references "user",
            entity text null,
            entity_id bigint null,
            ip_address inet null,
            user_agent text null,
            trace_id char(32) null,
            span_id char(16) null,
            message text null,
            "data" jsonb null
        )
        SQL);

        $this->addSql(<<<SQL
        create view reporting.audit as
        select
            id,
            created_at,
            action
        from public.audit
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('drop view reporting.audit');
        $this->addSql('drop table audit');
    }
}
