services:

  victorialogs:
    image: victoriametrics/victoria-logs:v1.51.0
    restart: no
    volumes:
      - victorialogs:/victoria-logs-data
    command:
      - "-storageDataPath=/victoria-logs-data"
      - "-retentionPeriod=60d"   # Keep logs for 60 days
      - "-defaultMsgValue=empty" # Fallback so logs aren't dropped

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.147.0
    restart: no
    command:
      - "-storageDataPath=/victoria-metrics-data"
      - "-retentionPeriod=12"
      - "-httpListenAddr=:8428"
    volumes:
      - victoriametrics:/victoria-metrics-data

  vector:
    image: timberio/vector:0.57.0.custom.3d46266-distroless-libc
    restart: no
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker:/var/lib/docker:ro
      - ./observability/vector.yaml:/etc/vector/vector.yaml:ro
    depends_on:
      - victorialogs

  grafana:
    image: grafana/grafana-oss:13.0.2
    depends_on:
      - victorialogs
    restart: no
    secrets:
      - admin_password
      - role_reporting_password
    environment:
      GF_SECURITY_ADMIN_EMAIL: ${ADMIN_EMAIL}
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/admin_password
      GF_USERS_DEFAULT_THEME: system
      GF_USERS_ALLOW_SIGN_UP: false
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_PLUGINS_PREINSTALL: victoriametrics-logs-datasource
    volumes:
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro

  # Mot de passe chiffré avec bcrypt. Attention le caractère $ doit être doublé !
  ntfy:
    image: binwiederhier/ntfy:v2.26
    restart: no
    environment:
      NTFY_BASE_URL: https://ntfy.localhost
      NTFY_BEHIND_PROXY: true
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_AUTH_USERS: 'admin:$$2y$$10$$guNukxQ4DA9AZVVY12cCyuYPXIfa2vdwANDXbkfmMzfLCUPxuxJcm:admin' # Must escape '$' as '$$'
      NTFY_ENABLE_LOGIN: true
      NTFY_REQUIRE_LOGIN: true
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
    volumes:
      - ntfy:/var/lib/ntfy
    command: serve

volumes:
  victorialogs:
  victoriametrics:
  grafana:
  ntfy:
